/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.modelvozila;

import common.domain.DomainObject;
import common.domain.ModelVozila;
import common.domain.NacinPlacanja;
import common.util.QueryFilter;
import java.time.LocalDate;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import logic.ModelVozilaKontroler;
import ui.general.CBModelDomainObject;
import ui.general.NavigacijaForma;
import ui.general.Notification;

/**
 *
 * @author danic
 */
public class PrikaziModelVozilaTabelaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziModelVozilaTabelaForma.class.getName());

     private List<DomainObject> modelvozilalist;
//     private List<String>
    /**
     * Creates new form PrikaziModelVozilaTabelaForma
     */
    public PrikaziModelVozilaTabelaForma() {
        initComponents();
        modelvozilalist = ModelVozilaKontroler.getInstance().vratiListuSviModelVozila();
        tabela.setModel(new ModelVozilaTableModel(modelvozilalist));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        nazadButton = new javax.swing.JButton();
        novoButton = new javax.swing.JButton();
        pronadjiButton = new javax.swing.JButton();
        primeniButton = new javax.swing.JButton();
        bezKriterijumaRadio = new javax.swing.JRadioButton();
        nazivModelaRadio = new javax.swing.JRadioButton();
        nazivMarkeRaio = new javax.swing.JRadioButton();
        modelVozilaIDRadio = new javax.swing.JRadioButton();
        mvidTF = new javax.swing.JTextField();
        modelTF = new javax.swing.JTextField();
        markaTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Pregled modela vozila");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        nazadButton.setText("Nazad");
        nazadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazadButtonActionPerformed(evt);
            }
        });

        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        pronadjiButton.setText("Pronađi");
        pronadjiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronadjiButtonActionPerformed(evt);
            }
        });

        primeniButton.setText("Primeni");
        primeniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeniButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(bezKriterijumaRadio);
        bezKriterijumaRadio.setSelected(true);
        bezKriterijumaRadio.setText("Bez kriterijuma");

        buttonGroup1.add(nazivModelaRadio);
        nazivModelaRadio.setText("Naziv modela");

        buttonGroup1.add(nazivMarkeRaio);
        nazivMarkeRaio.setText("Naziv marke");
        nazivMarkeRaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazivMarkeRaioActionPerformed(evt);
            }
        });

        buttonGroup1.add(modelVozilaIDRadio);
        modelVozilaIDRadio.setText("ModelVozilaID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nazadButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(novoButton)
                                .addGap(18, 18, 18)
                                .addComponent(pronadjiButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nazivMarkeRaio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(markaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bezKriterijumaRadio)
                                            .addComponent(primeniButton))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(modelVozilaIDRadio)
                                            .addComponent(nazivModelaRadio))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mvidTF, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bezKriterijumaRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelVozilaIDRadio)
                            .addComponent(mvidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazivModelaRadio)
                            .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazivMarkeRaio)
                            .addComponent(markaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(primeniButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazadButton)
                    .addComponent(novoButton)
                    .addComponent(pronadjiButton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pronadjiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronadjiButtonActionPerformed
        int index = tabela.getSelectedRow();
        if(index < 0){
            Notification.showErrorMessage(this, "Molimo izaberite model vozila!");
            return;
        }
        ModelVozila izabrano = (ModelVozila)modelvozilalist.get(index);
        izabrano.setQueryFilter(new QueryFilter(izabrano));
        ModelVozila pronadjeno = (ModelVozila)ModelVozilaKontroler.getInstance().pronadjiModelVozila(izabrano);
        if(pronadjeno == null){
            Notification.showErrorMessage(this, "Sistem nije uspeo da pronađe model vozila.");
            return;
        }
        Notification.showInfoMessage(this, "Sistem je pronašao model vozila.");
        new PrikaziModelVozilaForma(pronadjeno).setVisible(true);
        dispose();
    }//GEN-LAST:event_pronadjiButtonActionPerformed

    private void nazadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazadButtonActionPerformed
        new NavigacijaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_nazadButtonActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        new KreirajModelVozilaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_novoButtonActionPerformed

    private void primeniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeniButtonActionPerformed
        
        if(bezKriterijumaRadio.isSelected()){
            modelvozilalist = ModelVozilaKontroler.getInstance().vratiListuSviModelVozila();
        }

        if(modelVozilaIDRadio.isSelected()){
            long id;
            try {
                id = Long.parseLong(mvidTF.getText());
            } catch (Exception e) {
                Notification.showErrorMessage(this, "Neispravan unos za pretragu modela vozila");
                return;
            }
            ModelVozila mv = new ModelVozila(id, null, null, 0);
            mv.setQueryFilter(new QueryFilter(mv));
            modelvozilalist = ModelVozilaKontroler.getInstance().vratiListuModelVozila(mv);
        }
        
        if(nazivModelaRadio.isSelected()){
            String model = modelTF.getText().trim();
            ModelVozila mv = new ModelVozila(0, model, "", 0);
            mv.setQueryFilter(mv.generateQueryMask(false, true, false, false)); 
            modelvozilalist = ModelVozilaKontroler.getInstance().vratiListuModelVozila(mv);
        }
        
        if(nazivMarkeRaio.isSelected()){
            String marka = markaTF.getText().trim();
            ModelVozila mv = new ModelVozila(0, "", marka, 0);
            mv.setQueryFilter(mv.generateQueryMask(false, false, true, false));
            modelvozilalist = ModelVozilaKontroler.getInstance().vratiListuModelVozila(mv);
        }
        
        if(modelvozilalist.isEmpty()){
            Notification.showErrorMessage(this, "Sistem nije uspeo da nađe model vozila prema zadatim kriterijumima");
        }else{
            Notification.showInfoMessage(this, "Sistem je uspeo da nađe model vozila prema zadatim kriterijumima");
        }
        tabela.setModel(new ModelVozilaTableModel(modelvozilalist));
    }//GEN-LAST:event_primeniButtonActionPerformed

    private void nazivMarkeRaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazivMarkeRaioActionPerformed
         
    }//GEN-LAST:event_nazivMarkeRaioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrikaziModelVozilaTabelaForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bezKriterijumaRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField markaTF;
    private javax.swing.JTextField modelTF;
    private javax.swing.JRadioButton modelVozilaIDRadio;
    private javax.swing.JTextField mvidTF;
    private javax.swing.JButton nazadButton;
    private javax.swing.JRadioButton nazivMarkeRaio;
    private javax.swing.JRadioButton nazivModelaRadio;
    private javax.swing.JButton novoButton;
    private javax.swing.JButton primeniButton;
    private javax.swing.JButton pronadjiButton;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
