/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.modelvozila;

import common.domain.ModelVozila;
import common.util.QueryFilter;
import logic.ModelVozilaKontroler;
import ui.general.Notification;

/**
 *
 * @author danic
 */
public class PrikaziModelVozilaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziModelVozilaForma.class.getName());

    /**
     * Creates new form PrikaziModelVozilaForma
     */
    private ModelVozila mv;
    
    public PrikaziModelVozilaForma() {
        initComponents();
    }
    
    public PrikaziModelVozilaForma(ModelVozila mv){
        initComponents();
        this.mv = mv;
        long id = mv.getIdModelVozila();
        idTF.setText(Long.toString(id));
        nazivmodelaTF.setText(mv.getNazivModela());
        nazivmarkeTF.setText(mv.getNazivMarke());
        godisteTF.setText(Integer.toString(mv.getGodiste()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        nazivmodelaTF = new javax.swing.JTextField();
        nazivmarkeTF = new javax.swing.JTextField();
        godisteTF = new javax.swing.JTextField();
        nazadButton = new javax.swing.JButton();
        obrisiButton = new javax.swing.JButton();
        promeniButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Prikaz modela vozila");

        jLabel2.setText("ID");

        jLabel3.setText("Naziv modela");

        jLabel4.setText("Naziv marke");

        jLabel5.setText("Godište");

        idTF.setEditable(false);

        nazadButton.setText("Nazad");
        nazadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazadButtonActionPerformed(evt);
            }
        });

        obrisiButton.setText("Obriši");
        obrisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiButtonActionPerformed(evt);
            }
        });

        promeniButton.setText("Promeni");
        promeniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promeniButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nazadButton)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(godisteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nazivmodelaTF)
                                .addComponent(nazivmarkeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(obrisiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(promeniButton)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nazivmodelaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nazivmarkeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(godisteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazadButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(obrisiButton)
                        .addComponent(promeniButton)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nazadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazadButtonActionPerformed
        new PrikaziModelVozilaTabelaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_nazadButtonActionPerformed

    private void promeniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promeniButtonActionPerformed
        String nazivmod = nazivmodelaTF.getText();
        String nazivmark = nazivmarkeTF.getText();
        int godiste;
        try {
            godiste = Integer.parseInt(godisteTF.getText());
        } catch (Exception e) {
            Notification.showErrorMessage(this, "Sistem ne može da zapamti model vozila");
            return;
        }
        if(godiste < 1970 || godiste > 2026){
            Notification.showErrorMessage(this, "Sistem ne može da zapamti model vozila");
            return;
        }

        ModelVozila novo = new ModelVozila(mv.getIdModelVozila(), nazivmod, nazivmark, godiste);
        boolean signal = ModelVozilaKontroler.getInstance().promeniModelVozila(novo);
        if(signal != true){
            Notification.showErrorMessage(this, "Sistem ne može da zapampti model vozila");
            return;
        }
        Notification.showInfoMessage(this, "Sistem je zapamtio model vozila");
        new PrikaziModelVozilaTabelaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_promeniButtonActionPerformed

    private void obrisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiButtonActionPerformed
        mv.setQueryFilter(new QueryFilter(mv));
        boolean signal = ModelVozilaKontroler.getInstance().obrisiModelVozila(mv);
        if(signal == true){
            Notification.showInfoMessage(this, "Sistem je obrisao model vozila");
            new PrikaziModelVozilaTabelaForma().setVisible(true);
            dispose();
            return;
        }
        Notification.showErrorMessage(this, "Sistem nije uspeo da obriše model vozila");
    }//GEN-LAST:event_obrisiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrikaziModelVozilaForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField godisteTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton nazadButton;
    private javax.swing.JTextField nazivmarkeTF;
    private javax.swing.JTextField nazivmodelaTF;
    private javax.swing.JButton obrisiButton;
    private javax.swing.JButton promeniButton;
    // End of variables declaration//GEN-END:variables
}
