/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.radnik;

import common.domain.DomainObject;
import common.domain.Radnik;
import logic.RadnikKontroler;
import logic.SessionManager;
import java.util.List;
import ui.general.NavigacijaForma;
import ui.general.Notification;

/**
 *
 * @author danic
 */
public class FormaLogovanje extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormaLogovanje.class.getName());

    /**
     * Creates new form FormaLogovanje
     */
    public FormaLogovanje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameTextField = new javax.swing.JTextField();
        PrijaviButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        ShowPasswordCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UsernameTextField.setText("ana");

        PrijaviButton.setText("Uloguj se");
        PrijaviButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrijaviButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Korisničko ime:");

        jLabel2.setText("Šifra:");

        PasswordField.setText("pass2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Prijavi radnika");

        ShowPasswordCheckBox.setText("Prikaži šifru");
        ShowPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(UsernameTextField)
                    .addComponent(PasswordField)
                    .addComponent(PrijaviButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ShowPasswordCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(ShowPasswordCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PrijaviButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordCheckBoxActionPerformed
        if(ShowPasswordCheckBox.isSelected()){
            PasswordField.setEchoChar((char)0);
            return;
        }
        PasswordField.setEchoChar('•');
    }//GEN-LAST:event_ShowPasswordCheckBoxActionPerformed

    private void PrijaviButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrijaviButtonActionPerformed
        loginProcedure();
    }//GEN-LAST:event_PrijaviButtonActionPerformed

    private void loginProcedure(){
        Radnik user = new Radnik(UsernameTextField.getText(), new String(PasswordField.getPassword()));
        
        boolean signal = RadnikKontroler.getInstance().prijaviRadnik(user);
        if(signal == true){
            Notification.showInfoMessage(this, "Korisničko ime i šifra su ispravni!");
            Radnik ulogovani = new Radnik();
            ulogovani.setQueryFilter(user.generateQueryMask(false, false, false, false, false, false, true, false));
            
            //System.out.println("QUERY MASK EXISTS? " + user.isQueryMaskSet());
            List<DomainObject> list = RadnikKontroler.getInstance().vratiListuRadnik(ulogovani);
            if(list == null || list.isEmpty()){
                System.out.println("LOGIN ERROR: logged on username does not exist");
                return;
            }
            SessionManager.getInstance().setUlogovani((Radnik)list.get(0));
            dispose();
            new NavigacijaForma().setVisible(true);
            //new PrikaziZaposleniTabelaForma().setVisible(true);
            //new PrikaziIznajmljivanjeTabelaForma().setVisible(true);
            return;
        }
        //JOptionPane.showMessageDialog(this, "Neuspešna prijava, proverite unete kredencijale");
        Notification.showErrorMessage(this, "Korisničko ime i šifra nisu ispravni");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormaLogovanje().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton PrijaviButton;
    private javax.swing.JCheckBox ShowPasswordCheckBox;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
