/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.radnik;

import common.domain.DomainObject;
import common.domain.Radnik;
import common.util.QueryFilter;
import logic.RadnikKontroler;
import logic.TerminKontroler;
import java.util.List;
import javax.swing.JOptionPane;
import ui.general.CBModelDomainObject;
import ui.general.NavigacijaForma;
import ui.general.Notification;

/**
 *
 * @author danic
 */
public class PrikaziRadnikTabelaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziRadnikTabelaForma.class.getName());

    /**
     * Creates new form PrikaziRadnikTabelaForma
     */
    
    private List<DomainObject> radnikList;
    private List<DomainObject> terminList;
    
    public PrikaziRadnikTabelaForma() {
        initComponents();
        radnikList = RadnikKontroler.getInstance().vratiListuSviRadnik();
        radnikTable.setModel(new RadnikTableModel(radnikList));
        kriterijumComboBox.setModel(new CBModelDomainObject());
        terminList = TerminKontroler.getInstance().vratiListuSviTermin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bezOgranicenjaRadio = new javax.swing.JRadioButton();
        TerminRadio = new javax.swing.JRadioButton();
        radnikRadioButton = new javax.swing.JRadioButton();
        radnikTextField = new javax.swing.JTextField();
        kriterijumComboBox = new javax.swing.JComboBox<>();
        primeniButton = new javax.swing.JButton();
        nazadButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        radnikTable = new javax.swing.JTable();
        noviButton = new javax.swing.JButton();
        pretraziButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Pregled radnika");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Odabir kriterijuma:");

        buttonGroup1.add(bezOgranicenjaRadio);
        bezOgranicenjaRadio.setText("Bez kriterijuma");
        bezOgranicenjaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bezOgranicenjaRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(TerminRadio);
        TerminRadio.setText("Termin");
        TerminRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(radnikRadioButton);
        radnikRadioButton.setText("IDRadnik");

        kriterijumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        primeniButton.setText("Primeni");
        primeniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeniButtonActionPerformed(evt);
            }
        });

        nazadButton.setText("Nazad");
        nazadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazadButtonActionPerformed(evt);
            }
        });

        radnikTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(radnikTable);

        noviButton.setText("Dodaj nogov");
        noviButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noviButtonActionPerformed(evt);
            }
        });

        pretraziButton.setText("Pronađi");
        pretraziButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretraziButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nazadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(bezOgranicenjaRadio)
                            .addComponent(TerminRadio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radnikRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(radnikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kriterijumComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(primeniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(noviButton)
                        .addGap(18, 18, 18)
                        .addComponent(pretraziButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(412, 412, 412))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bezOgranicenjaRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TerminRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radnikRadioButton)
                            .addComponent(radnikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(kriterijumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(primeniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noviButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pretraziButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TerminRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminRadioActionPerformed
        kriterijumComboBox.setModel(new CBModelDomainObject(terminList));
    }//GEN-LAST:event_TerminRadioActionPerformed

    private void bezOgranicenjaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bezOgranicenjaRadioActionPerformed
        kriterijumComboBox.setModel(new CBModelDomainObject());
    }//GEN-LAST:event_bezOgranicenjaRadioActionPerformed

    private void primeniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeniButtonActionPerformed
        if(bezOgranicenjaRadio.isSelected()){
            radnikList = RadnikKontroler.getInstance().vratiListuSviRadnik();
            radnikTable.setModel(new RadnikTableModel(radnikList));
            return;
        }
        
        if(radnikRadioButton.isSelected()){
            long id;
            try {
                id = Long.parseLong(radnikTextField.getText());
            } catch (Exception e) {
                Notification.showErrorMessage(this, "Neispravan unos za pretragu zaposlenih");
                return;
            }
            Radnik rad = new Radnik(id, null, null, null, null, null, null, null);
            rad.setQueryFilter(new QueryFilter(rad));
            radnikList = RadnikKontroler.getInstance().vratiListuRadnik(rad);
            if(radnikList == null || radnikList.isEmpty()){
                Notification.showErrorMessage(this, "Sistem nije uspeo da nađe zaposlene po zadatom kriterijumu");
            }else{
                Notification.showInfoMessage(this, "Sistem je uspeo da nađe zaposlene po zadatom kriterijumu");
            }
            radnikTable.setModel(new RadnikTableModel(radnikList));
            return;
        }
        DomainObject ter = terminList.get(kriterijumComboBox.getSelectedIndex());
        DomainObject radnikk = new Radnik();
        radnikk.setQueryFilter(new QueryFilter(ter));
        radnikList = RadnikKontroler.getInstance().vratiListuRadnik(radnikk);
        if(radnikList == null || radnikList.isEmpty()){
            Notification.showErrorMessage(this, "Sistem nije uspeo da nađe zaposlene po zadatom kriterijumu");
        }else{
            Notification.showInfoMessage(this, "Sistem je uspeo da nađe zaposlene po zadatom kriterijumu");
        }
        radnikTable.setModel(new RadnikTableModel(radnikList));
    }//GEN-LAST:event_primeniButtonActionPerformed

    private void pretraziButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretraziButtonActionPerformed
        int selectedRow = radnikTable.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Red nije izabran!");
            return;
        }
        Radnik r = (Radnik)radnikList.get(selectedRow);
        r.setQueryFilter(new QueryFilter(r));
        r = (Radnik)RadnikKontroler.getInstance().pretraziRadnik(r);
        if(r == null){
            Notification.showErrorMessage(this, "Sistem nije uspeo da pronadje zaposlenog!");
            return;
        }
        Notification.showInfoMessage(this, "Sistem je pronasao zaposlenog!");
        new PrikaziRadnikForma(r).setVisible(true);
        dispose();
    }//GEN-LAST:event_pretraziButtonActionPerformed

    private void nazadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazadButtonActionPerformed
        new NavigacijaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_nazadButtonActionPerformed

    private void noviButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noviButtonActionPerformed
        new KreirajRadnikForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_noviButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrikaziRadnikTabelaForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton TerminRadio;
    private javax.swing.JRadioButton bezOgranicenjaRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kriterijumComboBox;
    private javax.swing.JButton nazadButton;
    private javax.swing.JButton noviButton;
    private javax.swing.JButton pretraziButton;
    private javax.swing.JButton primeniButton;
    private javax.swing.JRadioButton radnikRadioButton;
    private javax.swing.JTable radnikTable;
    private javax.swing.JTextField radnikTextField;
    // End of variables declaration//GEN-END:variables
}
