/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.vozilo;

import common.domain.DomainObject;
import common.domain.ModelVozila;
import common.domain.TipVozila;
import common.domain.Vozilo;
import common.util.QueryFilter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import logic.ModelVozilaKontroler;
import logic.VoziloKontroler;
import ui.general.CBModelDomainObject;
import ui.general.Notification;

/**
 *
 * @author danic
 */
public class PrikaziVoziloForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziVoziloForma.class.getName());

    private Vozilo vozilo;
    private List<DomainObject> listModel;
    /**
     * Creates new form PrikaziVoziloForma
     */
    public PrikaziVoziloForma() {
        initComponents();
    }
    
    public PrikaziVoziloForma(Vozilo voz){
        initComponents();
        idTF.setText(Long.toString(voz.getIdVozilo()));
        nazivTF.setText(voz.getNazivVozila());
        vozilo = voz;
        
        listModel = ModelVozilaKontroler.getInstance().vratiListuSviModelVozila();
        modelCB.setModel(new CBModelDomainObject(listModel));
        
        switch(voz.getTipVozila()){
            case TERETNO:
                tipCB.setSelectedIndex(0);
                break;
            case PUTNICKO:
                tipCB.setSelectedIndex(1);
                break;
            case MOTOCIKL:
                tipCB.setSelectedIndex(2);
                break;
            case AUTOBUS:
                tipCB.setSelectedIndex(3);
                break;
            case KOMBI:
                tipCB.setSelectedIndex(4);
                break;
            case RADNA_MASINA:
                tipCB.setSelectedIndex(5);
                break;
            default:
                tipCB.setSelectedIndex(-1);
                break;
        }
        
        for(int i=0; i<listModel.size();i++){
            if(((ModelVozila)listModel.get(i)).getIdModelVozila()== voz.getModelVozila().getIdModelVozila()){
                modelCB.setSelectedIndex(i);
            }
        }
        
        //treba da bude selektovan tip vozila koje je otvoreno kao voz.getTip something
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        nazivTF = new javax.swing.JTextField();
        tipCB = new javax.swing.JComboBox<>();
        modelCB = new javax.swing.JComboBox<>();
        nazadButton = new javax.swing.JButton();
        obrisiButton = new javax.swing.JButton();
        potvrdiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Prikaz vozila");

        jLabel2.setText("ID");

        jLabel3.setText("Naziv vozila");

        jLabel4.setText("Tip vozila");

        jLabel5.setText("Model vozila");

        idTF.setEditable(false);

        nazivTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazivTFActionPerformed(evt);
            }
        });

        tipCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TERETNO", "PUTNICKO", "MOTOCIKL", "AUTOBUS", "KOMBI", " RADNA_MASINA" }));
        tipCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipCBActionPerformed(evt);
            }
        });

        modelCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nazadButton.setText("Nazad");
        nazadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazadButtonActionPerformed(evt);
            }
        });

        obrisiButton.setText("Obriši");
        obrisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiButtonActionPerformed(evt);
            }
        });

        potvrdiButton.setText("Potvrdi");
        potvrdiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potvrdiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(nazadButton)
                        .addGap(100, 100, 100)
                        .addComponent(obrisiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(potvrdiButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modelCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nazivTF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nazivTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modelCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazadButton)
                    .addComponent(obrisiButton)
                    .addComponent(potvrdiButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obrisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiButtonActionPerformed
        vozilo.setQueryFilter(new QueryFilter(vozilo)); // trazi samog sebe
        if(VoziloKontroler.getInstance().obrisiVozilo(vozilo) == true){
            Notification.showInfoMessage(this, "Vozilo uspešno obrisano");
            new PrikaziVoziloTabelaForma().setVisible(true);
            dispose();
            return;
        }
        Notification.showErrorMessage(this, "Sistem nije uspeo da obriše vozilo");
    }//GEN-LAST:event_obrisiButtonActionPerformed

    private void nazivTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazivTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nazivTFActionPerformed

    private void nazadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazadButtonActionPerformed
        new PrikaziVoziloTabelaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_nazadButtonActionPerformed

    private void potvrdiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potvrdiButtonActionPerformed
        TipVozila tip = TipVozila.valueOf((String) tipCB.getSelectedItem());
        vozilo = new Vozilo(Long.parseLong(idTF.getText()),
                nazivTF.getText(),
                tip,
                (ModelVozila)listModel.get(modelCB.getSelectedIndex())
        );
        vozilo.setQueryFilter(new QueryFilter(vozilo)); // trazi sebe
        if(VoziloKontroler.getInstance().promeniVozilo(vozilo) == true){
            Notification.showInfoMessage(this, "Sistem je uspešno izmenio vozilo");
            new PrikaziVoziloTabelaForma().setVisible(true);
            dispose();
            return;
        }
        Notification.showErrorMessage(this, "Sistem nije uspeo da promeni vozilo");
    }//GEN-LAST:event_potvrdiButtonActionPerformed

    private void tipCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrikaziVoziloForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> modelCB;
    private javax.swing.JButton nazadButton;
    private javax.swing.JTextField nazivTF;
    private javax.swing.JButton obrisiButton;
    private javax.swing.JButton potvrdiButton;
    private javax.swing.JComboBox<String> tipCB;
    // End of variables declaration//GEN-END:variables
}
