/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.vozilo;

import common.domain.DomainObject;
import common.domain.Vozilo;
import common.util.QueryFilter;
import java.util.List;
import logic.ModelVozilaKontroler;
import logic.VoziloKontroler;
import ui.general.CBModelDomainObject;
import ui.general.NavigacijaForma;
import ui.general.Notification;

/**
 *
 * @author danic
 */
public class PrikaziVoziloTabelaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziVoziloTabelaForma.class.getName());

    /**
     * Creates new form PrikaziVoziloTabelaForma
     */
    private List<DomainObject> listVozilo;
    private List<DomainObject> listModel;
    
    public PrikaziVoziloTabelaForma() {
        initComponents();
        listVozilo = VoziloKontroler.getInstance().vratiListuSviVozilo();
        tabela.setModel(new VoziloTableModel(listVozilo));
        kriterijumCB.setModel(new CBModelDomainObject());
        listModel = ModelVozilaKontroler.getInstance().vratiListuSviModelVozila();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bezKriterijumaRadioButton = new javax.swing.JRadioButton();
        idRadioButton = new javax.swing.JRadioButton();
        idTF = new javax.swing.JTextField();
        modelRadioButton = new javax.swing.JRadioButton();
        kriterijumCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        primeniButton = new javax.swing.JButton();
        nazadButton = new javax.swing.JButton();
        novoButton = new javax.swing.JButton();
        pronadjiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Pregled vozila");

        jLabel2.setText("Odabir kriterijuma:");

        bezKriterijumaRadioButton.setSelected(true);
        bezKriterijumaRadioButton.setText("Bez kriterijuma");

        idRadioButton.setText("VoziloID");

        modelRadioButton.setText("Model vozila");

        kriterijumCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        primeniButton.setText("Primeni");
        primeniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeniButtonActionPerformed(evt);
            }
        });

        nazadButton.setText("Nazad");
        nazadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazadButtonActionPerformed(evt);
            }
        });

        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        pronadjiButton.setText("Pronađi");
        pronadjiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronadjiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nazadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(novoButton)
                        .addGap(18, 18, 18)
                        .addComponent(pronadjiButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(modelRadioButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(idRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bezKriterijumaRadioButton)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(kriterijumCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(primeniButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(bezKriterijumaRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idRadioButton)
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modelRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kriterijumCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(primeniButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoButton)
                    .addComponent(pronadjiButton)
                    .addComponent(nazadButton))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nazadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazadButtonActionPerformed
        new NavigacijaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_nazadButtonActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        new KreirajVoziloForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_novoButtonActionPerformed

    private void pronadjiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronadjiButtonActionPerformed
        int selectedRow = tabela.getSelectedRow();
        if(selectedRow == -1){
            Notification.showErrorMessage(this, "Red nije izabran!");
            return;
        }
        Vozilo vozz = (Vozilo)listVozilo.get(selectedRow);
        vozz.setQueryFilter(new QueryFilter(vozz));
        Vozilo new_voz;
        new_voz = (Vozilo)VoziloKontroler.getInstance().pronadjiVozilo(vozz);
        if(new_voz != null){
            Notification.showInfoMessage(this, "Sistem je pronašao vozilo!");
            new PrikaziVoziloForma(new_voz).setVisible(true);
            dispose();
            return;
        }
        Notification.showErrorMessage(this, "Sistem nije uspeo da pronađe vozilo!");
    }//GEN-LAST:event_pronadjiButtonActionPerformed

    private void primeniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeniButtonActionPerformed
        if(bezKriterijumaRadioButton.isSelected()){
            listVozilo = VoziloKontroler.getInstance().vratiListuSviVozilo();
            tabela.setModel(new VoziloTableModel(listVozilo));
            return;
        }
        if(idRadioButton.isSelected()){
            long id;
            try {
                id = Long.parseLong(idTF.getText());
            } catch (Exception e) {
                Notification.showErrorMessage(this, "Neispravan unos za pretragu vozila");
                return;
            }
            Vozilo voz = new Vozilo(id, null, null, null);
            voz.setQueryFilter(new QueryFilter(voz));
            listVozilo = VoziloKontroler.getInstance().vratiListuVozilo(voz);
            if(listVozilo == null || listVozilo.isEmpty()){
                Notification.showErrorMessage(this, "Sistem nije pronašao vozila po zadatom kriterijumu");
            }else{
                Notification.showInfoMessage(this, "Sistem je pronašao vozila po zadatom kriterijumu");
            }
            tabela.setModel(new VoziloTableModel(listVozilo));
            return;
        }
        DomainObject model = listModel.get(kriterijumCB.getSelectedIndex());
        DomainObject v = new Vozilo();
        v.setQueryFilter(new QueryFilter(model));
        listVozilo = VoziloKontroler.getInstance().vratiListuVozilo(v);
        if(listVozilo == null || listVozilo.isEmpty()){
            Notification.showErrorMessage(this, "Sistem nije pronašao vozila po zadatom kriterijumu");
        }else{
            Notification.showInfoMessage(this, "Sistem je pronašao vozila po zadatom kriterijumu");
        }
        tabela.setModel(new VoziloTableModel(listVozilo));
    }//GEN-LAST:event_primeniButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrikaziVoziloTabelaForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bezKriterijumaRadioButton;
    private javax.swing.JRadioButton idRadioButton;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kriterijumCB;
    private javax.swing.JRadioButton modelRadioButton;
    private javax.swing.JButton nazadButton;
    private javax.swing.JButton novoButton;
    private javax.swing.JButton primeniButton;
    private javax.swing.JButton pronadjiButton;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
