/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.servoper;

import common.domain.DomainObject;
import common.domain.ServisnaOperacija;
import common.domain.TipServOper;
import common.util.QueryFilter;
import java.time.LocalDate;
import java.util.List;
import logic.ServOperKontroler;
import ui.general.NavigacijaForma;
import ui.general.Notification;

/**
 *
 * @author danic
 */
public class PrikaziServOperTabelaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziServOperTabelaForma.class.getName());

    /**
     * Creates new form PrikaziServOperTabelaForma
     */
    
    private List<DomainObject> listaservoper;
    
    public PrikaziServOperTabelaForma() {
        initComponents();
        listaservoper = ServOperKontroler.getInstance().vratiListuSviServOper();
        tabela.setModel(new ServOperTableModel(listaservoper));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bezKriterijumaRadio = new javax.swing.JRadioButton();
        servOperIdRadio = new javax.swing.JRadioButton();
        servOperIDTF = new javax.swing.JTextField();
        tipServOperRadio = new javax.swing.JRadioButton();
        tipCB = new javax.swing.JComboBox<>();
        primeniButton = new javax.swing.JButton();
        nazadButton = new javax.swing.JButton();
        pronadjiButton = new javax.swing.JButton();
        novoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Pregled servisnih operacija");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel2.setText("Odabir kriterijuma:");

        buttonGroup1.add(bezKriterijumaRadio);
        bezKriterijumaRadio.setSelected(true);
        bezKriterijumaRadio.setText("Bez kriterijuma");

        buttonGroup1.add(servOperIdRadio);
        servOperIdRadio.setText("ServOperID");
        servOperIdRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servOperIdRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(tipServOperRadio);
        tipServOperRadio.setText("Tip servisne operacije");

        tipCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUTINSKI_SERVIS", "KOCIONI_SISTEM", "VESANJE_I_UPRAVLJACKI_SISTEM", "MOTOR_I_PRENOS", "ELEKTRONIKA_I_ELEKTROINSTALACIJE", "KAROSERIJA_I_SPOLJASNJE_FUNKCIJE", "KLIMA_I_GREJANJE", "SPECIJALNI_SERVISI" }));

        primeniButton.setText("Primeni");
        primeniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeniButtonActionPerformed(evt);
            }
        });

        nazadButton.setText("Nazad");
        nazadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazadButtonActionPerformed(evt);
            }
        });

        pronadjiButton.setText("Pronađi");
        pronadjiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronadjiButtonActionPerformed(evt);
            }
        });

        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nazadButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(novoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pronadjiButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(bezKriterijumaRadio)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(servOperIdRadio)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(servOperIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(tipServOperRadio)
                                        .addComponent(tipCB, 0, 0, Short.MAX_VALUE))
                                    .addComponent(primeniButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(bezKriterijumaRadio)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(servOperIdRadio)
                            .addComponent(servOperIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipServOperRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(primeniButton)
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazadButton)
                    .addComponent(pronadjiButton)
                    .addComponent(novoButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void servOperIdRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servOperIdRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servOperIdRadioActionPerformed

    private void primeniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeniButtonActionPerformed
        if(bezKriterijumaRadio.isSelected()){
            listaservoper = ServOperKontroler.getInstance().vratiListuSviServOper();
            tabela.setModel(new ServOperTableModel(listaservoper));
            return;
        }
        
        if(servOperIdRadio.isSelected()){
            long id;
            try {
                id = Long.parseLong(servOperIDTF.getText());
            } catch (Exception e) {
                Notification.showErrorMessage(this, "Neispravan unos za pretragu servisne operacije");
                return;
            }
            ServisnaOperacija mas = new ServisnaOperacija(id, null, TipServOper.RUTINSKI_SERVIS, 0);
            mas.setQueryFilter(new QueryFilter(mas));
            listaservoper = ServOperKontroler.getInstance().vratiListuServOper(mas);
            if(listaservoper != null && listaservoper.isEmpty() == false){
                Notification.showInfoMessage(this, "Sistem je našao servisne operacije po zadatom kriterijumu");
            }else{
                Notification.showErrorMessage(this, "Sistem ne može da nađe servisne operacije po zadatom kriterijumu");
            }
            tabela.setModel(new ServOperTableModel(listaservoper));
            return;
        }
        
        TipServOper tip = TipServOper.values()[tipCB.getSelectedIndex()];
        ServisnaOperacija obj = new ServisnaOperacija(), filter = new ServisnaOperacija("n/a", tip , 1);
        obj.setQueryFilter(filter.generateQueryMask(false, false, true, false));
        listaservoper = ServOperKontroler.getInstance().vratiListuServOper(obj);
        if(listaservoper != null && listaservoper.isEmpty() == false){
            Notification.showInfoMessage(this, "Sistem je našao servisne operacije po zadatom kriterijumu");
        }else{
            Notification.showErrorMessage(this, "Sistem ne može da nađe servisne operacije po zadatom kriterijumu");
        }
        tabela.setModel(new ServOperTableModel(listaservoper));
    }//GEN-LAST:event_primeniButtonActionPerformed

    private void pronadjiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronadjiButtonActionPerformed
        int selectedRow = tabela.getSelectedRow();
        if(selectedRow == -1){
            Notification.showErrorMessage(this, "Red nije izabran!");
            return;
        }
        ServisnaOperacija so = (ServisnaOperacija)listaservoper.get(selectedRow);
        so.setQueryFilter(new QueryFilter(so));
        ServisnaOperacija new_mas;
        new_mas = (ServisnaOperacija)ServOperKontroler.getInstance().pronadjiServOper(so);
        if(new_mas != null){
            Notification.showInfoMessage(this, "Sistem je pronašao mašinu");
            new PrikaziServOperForma(new_mas).setVisible(true);
            dispose();
            return;
        }
        Notification.showErrorMessage(this, "Sistem nije uspeo da pronađe mašinu");
    }//GEN-LAST:event_pronadjiButtonActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        new KreirajServOperForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_novoButtonActionPerformed

    private void nazadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazadButtonActionPerformed
        new NavigacijaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_nazadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrikaziServOperTabelaForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bezKriterijumaRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nazadButton;
    private javax.swing.JButton novoButton;
    private javax.swing.JButton primeniButton;
    private javax.swing.JButton pronadjiButton;
    private javax.swing.JTextField servOperIDTF;
    private javax.swing.JRadioButton servOperIdRadio;
    private javax.swing.JTable tabela;
    private javax.swing.JComboBox<String> tipCB;
    private javax.swing.JRadioButton tipServOperRadio;
    // End of variables declaration//GEN-END:variables
}
