/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.servnalog;

import common.domain.DomainObject;
import common.domain.NacinPlacanja;
import common.domain.Radnik;
import common.domain.ServNalog;
import common.domain.ServisnaOperacija;
import common.domain.StavkaServisa;
import common.domain.Vozilo;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import logic.ServNalogKontroler;
import ui.general.CBModelDomainObject;
import ui.general.Notification;

/**
 *
 * @author danic
 */
public class PrikaziSrvNalogForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziSrvNalogForma.class.getName());

    
    /**
     * Creates new form PrikaziSrvNalogForma
     */
    public PrikaziSrvNalogForma() {
        initComponents();
    }
    
    private List<DomainObject> listRadnik;
    private List<DomainObject> listVozilo;
    private List<DomainObject> listStavkaServisa;
    private List<DomainObject> listServOper;
    private ServNalog servnalog;
    
    public PrikaziSrvNalogForma(List<DomainObject> listRadnik, List<DomainObject> listVozilo, List<DomainObject> listServOper, ServNalog servnalog) {
        initComponents();
        this.servnalog = servnalog;
        this.listRadnik = listRadnik;
        CBRadnik.setModel(new CBModelDomainObject(listRadnik));
        this.listVozilo = listVozilo;
        CBVozilo.setModel(new CBModelDomainObject(listVozilo));
        this.listServOper = listServOper;
        CBServOper.setModel(new CBModelDomainObject(listServOper));
        datumTF.setText(getDateFormatted());
        idLabel.setText(servnalog.getIdServNalog()+"");
        
        listStavkaServisa = servnalog.getStavkaServislista();
        tabela.setModel(new StavkaServisaTableModel(listStavkaServisa));
        
        int index_k = 0;
        int index_z = 0;
        
        for(DomainObject i : listVozilo){
            if(((Vozilo)i).getIdVozilo()== servnalog.getVozilo().getIdVozilo()){
                index_k = listVozilo.indexOf(i);
            }
        }
        
        for(DomainObject i : listRadnik){
            if(((Radnik)i).getIdRadnik()== servnalog.getRadnik().getIdRadnik()){
                index_z = listRadnik.indexOf(i);
            }
        }
        
        if(servnalog.getNacinPlacanja().equals(NacinPlacanja.KARTICA))
            placanjeCB.setSelectedIndex(1);
        
        CBRadnik.setSelectedIndex(index_z);
        CBVozilo.setSelectedIndex(index_k);
        
        postaviUkupnuCenu();
    }
    
    private String getDateFormatted() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy.");
        return servnalog.getDatum().format(formatter);
    }
    
    private void postaviUkupnuCenu(){
        if(servnalog.getStavkaServislista().isEmpty()){
            ukupnaCenaTextField.setText(Double.toString(0));
            return;
        }
        double suma = 0;
        for(DomainObject i : servnalog.getStavkaServislista()){
            suma += ((StavkaServisa)i).getCenaStavke();
        }
        if(suma != servnalog.getUkupnaCena()){
            //JOptionPane.showMessageDialog(this, "UPOZORENJE: ovaj dokument koristi cene koje više nisu važeće");
        }
        ukupnaCenaTextField.setText(Double.toString(suma));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datumTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CBRadnik = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CBVozilo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CBServOper = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        placanjeCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        dodajStavkuButton = new javax.swing.JButton();
        nazadButton = new javax.swing.JButton();
        ukloniButton = new javax.swing.JButton();
        potvrdiButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ukupnaCenaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kolicinaTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Upravljanje servisnim nalogom");

        jLabel2.setText("ID:");

        idLabel.setText("id");

        jLabel3.setText("Datum podnošenja:");

        datumTF.setEditable(false);
        datumTF.setText("01/01/1970");

        jLabel4.setText("Radnik:");

        CBRadnik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Vozilo:");

        CBVozilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Dodavanje stavke");

        CBServOper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Način plaćanja:");

        placanjeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gotovina", "Kartica" }));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        dodajStavkuButton.setText("Dodaj stavku");
        dodajStavkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStavkuButtonActionPerformed(evt);
            }
        });

        nazadButton.setText("Nazad");
        nazadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazadButtonActionPerformed(evt);
            }
        });

        ukloniButton.setText("Ukloni stavku");
        ukloniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukloniButtonActionPerformed(evt);
            }
        });

        potvrdiButton.setText("Potvrdi");
        potvrdiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potvrdiButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Ukupna cena:");

        jLabel9.setText("Količina:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nazadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dodajStavkuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(ukupnaCenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kolicinaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idLabel))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(datumTF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CBServOper, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(placanjeCB, javax.swing.GroupLayout.Alignment.LEADING, 0, 132, Short.MAX_VALUE)
                        .addComponent(CBVozilo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBRadnik, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ukloniButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(potvrdiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(261, 261, 261))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placanjeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBServOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(kolicinaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(dodajStavkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ukupnaCenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ukloniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potvrdiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajStavkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajStavkuButtonActionPerformed
        ServisnaOperacija so = (ServisnaOperacija)listServOper.get(CBServOper.getSelectedIndex());
        int kol = Integer.parseInt(kolicinaTF.getText());
        double cenastavke = so.getCenaServOper() * kol;
        StavkaServisa stv;
        stv = new StavkaServisa(Long.parseLong(idLabel.getText()),listStavkaServisa.size()+1, cenastavke, kol, so);
        listStavkaServisa.add(stv);
        tabela.setModel(new StavkaServisaTableModel(listStavkaServisa));

        postaviUkupnuCenu();
    }//GEN-LAST:event_dodajStavkuButtonActionPerformed

    private void ukloniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukloniButtonActionPerformed
        int index = tabela.getSelectedRow();
        if(index == -1)
            return;
        StavkaServisa stavka = (StavkaServisa) listStavkaServisa.get(index);
        //double iznos = Double.parseDouble(ukupnaCenaTextField.getText()) - stv.getCenaStavke();
        listStavkaServisa.remove(index);
        tabela.setModel(new StavkaServisaTableModel(listStavkaServisa));
        //ukupnaCenaTextField.setText(Double.toString(iznos));
        postaviUkupnuCenu();
    }//GEN-LAST:event_ukloniButtonActionPerformed

    private void potvrdiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potvrdiButtonActionPerformed
        Radnik radnik = (Radnik)listRadnik.get(CBRadnik.getSelectedIndex());
        Vozilo voz = (Vozilo) listVozilo.get(CBVozilo.getSelectedIndex());
        NacinPlacanja np = NacinPlacanja.GOTOVINA;
        if(placanjeCB.getSelectedIndex() > 0){
            np = NacinPlacanja.KARTICA;
        }
        double ukupnaCena = Double.parseDouble(ukupnaCenaTextField.getText());
        ServNalog new_servnalog = new ServNalog(Long.parseLong(idLabel.getText()), servnalog.getDatum(), ukupnaCena, np, radnik, voz, listStavkaServisa);
        boolean signal = ServNalogKontroler.getInstance().promeniServNalog(new_servnalog);
        if(signal){
            Notification.showInfoMessage(this, "Sistem je uspešno zapamtio servisni nalog");
            dispose();
            new PrikaziServNalogTabelaForma().setVisible(true);
            return;
        }
        Notification.showErrorMessage(this, "Sistem nije uspešno zapamtio servisni nalog");
    }//GEN-LAST:event_potvrdiButtonActionPerformed

    private void nazadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazadButtonActionPerformed
        new PrikaziServNalogTabelaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_nazadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrikaziSrvNalogForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBRadnik;
    private javax.swing.JComboBox<String> CBServOper;
    private javax.swing.JComboBox<String> CBVozilo;
    private javax.swing.JTextField datumTF;
    private javax.swing.JButton dodajStavkuButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kolicinaTF;
    private javax.swing.JButton nazadButton;
    private javax.swing.JComboBox<String> placanjeCB;
    private javax.swing.JButton potvrdiButton;
    private javax.swing.JTable tabela;
    private javax.swing.JButton ukloniButton;
    private javax.swing.JTextField ukupnaCenaTextField;
    // End of variables declaration//GEN-END:variables


}
