/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.termin;

import common.domain.DomainObject;
import common.domain.Radnik;
import common.domain.Smena;
import common.domain.Termin;
import common.util.QueryFilter;
import java.time.LocalDate;
import java.util.List;
import logic.RadnikKontroler;
import logic.TerminKontroler;
import ui.general.CBModelDomainObject;
import ui.general.NavigacijaForma;
import ui.general.Notification;

/**
 *
 * @author danic
 */
public class PrikaziTerminTabelaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziTerminTabelaForma.class.getName());

    /**
     * Creates new form PrikaziTerminTabelaForma
     */
    private List<DomainObject> terminList, radnikList;
    
    public PrikaziTerminTabelaForma() {
        initComponents();
        terminList = TerminKontroler.getInstance().vratiListuSviTermin();
        radnikList = RadnikKontroler.getInstance().vratiListuSviRadnik();
        tabela.setModel(new TerminTableModel(terminList));
        kriterijumCB.setModel(new CBModelDomainObject());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bezKriterijumaRadio = new javax.swing.JRadioButton();
        smenaRadio = new javax.swing.JRadioButton();
        radnikRadio = new javax.swing.JRadioButton();
        terminIdRadio = new javax.swing.JRadioButton();
        terminIdTF = new javax.swing.JTextField();
        kriterijumCB = new javax.swing.JComboBox<>();
        primeniButton = new javax.swing.JButton();
        nazadButton = new javax.swing.JButton();
        ubaciButton = new javax.swing.JButton();
        pronadjiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Pregled termina");

        buttonGroup1.add(bezKriterijumaRadio);
        bezKriterijumaRadio.setSelected(true);
        bezKriterijumaRadio.setText("Bez kriterijuma");
        bezKriterijumaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bezKriterijumaRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(smenaRadio);
        smenaRadio.setText("Smena");
        smenaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smenaRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(radnikRadio);
        radnikRadio.setText("Radnik");
        radnikRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radnikRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(terminIdRadio);
        terminIdRadio.setText("Termin ID");
        terminIdRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminIdRadioActionPerformed(evt);
            }
        });

        kriterijumCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        primeniButton.setText("Primeni");
        primeniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeniButtonActionPerformed(evt);
            }
        });

        nazadButton.setText("Nazad");
        nazadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazadButtonActionPerformed(evt);
            }
        });

        ubaciButton.setText("Ubaci");
        ubaciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubaciButtonActionPerformed(evt);
            }
        });

        pronadjiButton.setText("Pronađi");
        pronadjiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronadjiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bezKriterijumaRadio)
                            .addComponent(smenaRadio)
                            .addComponent(radnikRadio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(terminIdRadio)
                                .addGap(18, 18, 18)
                                .addComponent(terminIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primeniButton)
                                    .addComponent(kriterijumCB, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nazadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ubaciButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pronadjiButton)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bezKriterijumaRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(smenaRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radnikRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(terminIdRadio)
                            .addComponent(terminIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(kriterijumCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(primeniButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazadButton)
                            .addComponent(ubaciButton)
                            .addComponent(pronadjiButton))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(68, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nazadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazadButtonActionPerformed
        new NavigacijaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_nazadButtonActionPerformed

    private void primeniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeniButtonActionPerformed
        if(bezKriterijumaRadio.isSelected()){
            terminList = TerminKontroler.getInstance().vratiListuSviTermin();
        }
        
        if(terminIdRadio.isSelected()){
            long id;
            try {
                id = Long.parseLong(terminIdTF.getText());
            } catch (Exception e) {
                Notification.showErrorMessage(this, "Neispravan unos za pretragu termina");
                return;
            }
            Termin ter = new Termin(id, LocalDate.MIN, Smena.PRVA, null);
            ter.setQueryFilter(new QueryFilter(ter));
            terminList = TerminKontroler.getInstance().vratiListuTermin(ter);
        }
        
        // mhm u redu
        if(smenaRadio.isSelected()){
            String value = (String)kriterijumCB.getSelectedItem();
            Smena smena = Smena.valueOf(value);
            Termin td = new Termin(LocalDate.MIN, smena, null);
            td.setQueryFilter(td.generateQueryMask(false, false, true)); // trazi samo po smeni samog sebe (ok)
            terminList = TerminKontroler.getInstance().vratiListuTermin(td);
        }
        if(radnikRadio.isSelected()){
            Termin term = new Termin();
            Radnik z = (Radnik)radnikList.get(kriterijumCB.getSelectedIndex());
            term.setQueryFilter(new QueryFilter(z));
            terminList = TerminKontroler.getInstance().vratiListuTermin(term);
        }
        if(terminList.size() > 0){
            Notification.showInfoMessage(this, "Sistem je pronašao termine po zadatom kriterijumu");
        }else{
            Notification.showErrorMessage(this, "Sistem nije pronašao termine po zadatom kriterijumu");
        }
        tabela.setModel(new TerminTableModel(terminList));
    }//GEN-LAST:event_primeniButtonActionPerformed

    private void ubaciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubaciButtonActionPerformed
        new UbaciTerminForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_ubaciButtonActionPerformed

    private void pronadjiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronadjiButtonActionPerformed
        int index = tabela.getSelectedRow();
        if(index < 0){
            Notification.showErrorMessage(this, "Termin nije izabran!");
            return;
        }
        Termin stari = (Termin)terminList.get(index);
        stari.setQueryFilter(new QueryFilter(stari));
        Termin novi = (Termin)TerminKontroler.getInstance().pronadjiTermin(stari);
        if(novi == null){
            Notification.showErrorMessage(this, "Sistem nije uspeo da pronađe termin");
            return;
        }
        Notification.showInfoMessage(this, "Sistem je pronašao termin");
        new PrikaziTerminForma(novi).setVisible(true);
        dispose();
    }//GEN-LAST:event_pronadjiButtonActionPerformed

    private void terminIdRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminIdRadioActionPerformed
        kriterijumCB.setModel(new CBModelDomainObject());
    }//GEN-LAST:event_terminIdRadioActionPerformed

    private void radnikRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radnikRadioActionPerformed
        kriterijumCB.setModel(new CBModelDomainObject(radnikList));
    }//GEN-LAST:event_radnikRadioActionPerformed

    private void smenaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smenaRadioActionPerformed
        kriterijumCB.setModel(new CBModelDomainObject()); // resetuje combobox
        kriterijumCB.addItem("PRVA");
        kriterijumCB.addItem("DRUGA");
        kriterijumCB.addItem("TRECA");
    }//GEN-LAST:event_smenaRadioActionPerformed

    private void bezKriterijumaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bezKriterijumaRadioActionPerformed
        kriterijumCB.setModel(new CBModelDomainObject());
    }//GEN-LAST:event_bezKriterijumaRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrikaziTerminTabelaForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bezKriterijumaRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kriterijumCB;
    private javax.swing.JButton nazadButton;
    private javax.swing.JButton primeniButton;
    private javax.swing.JButton pronadjiButton;
    private javax.swing.JRadioButton radnikRadio;
    private javax.swing.JRadioButton smenaRadio;
    private javax.swing.JTable tabela;
    private javax.swing.JRadioButton terminIdRadio;
    private javax.swing.JTextField terminIdTF;
    private javax.swing.JButton ubaciButton;
    // End of variables declaration//GEN-END:variables
}
