/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.termin;

import common.domain.DomainObject;
import common.domain.Radnik;
import common.domain.Smena;
import common.domain.Termin;
import common.domain.TerminRadnika;
import common.domain.Uloga;
import common.util.QueryFilter;
import java.time.LocalDate;
import java.util.List;
import logic.DateChecker;
import logic.RadnikKontroler;
import logic.TerminKontroler;
import ui.general.CBModelDomainObject;
import ui.general.Notification;

/**
 *
 * @author danic
 */
public class PrikaziTerminForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziTerminForma.class.getName());

    /**
     * Creates new form TerminForma
     */
    private Termin termin;
    private List<DomainObject> listRadnik;
    
    public PrikaziTerminForma() {
        initComponents();
    }

    public PrikaziTerminForma(Termin term) {
        initComponents();
        this.termin = term;
        tabela.setModel(new TerminRadnikaModel(termin.getListaTerminaRadnika()));
        listRadnik = RadnikKontroler.getInstance().vratiListuSviRadnik();
        radnikCB.setModel(new CBModelDomainObject(listRadnik));
        
        //Uloga uloga = 
        
        LocalDate datum = term.getDatumTermina();
        danCB.setSelectedIndex(datum.getDayOfMonth() - 1); // indeksiranje niza offset
        mesecCB.setSelectedIndex(datum.getMonthValue() - 1);
        godinaCB.setSelectedIndex(datum.getYear() - 1970); // jer krece od 1970 u combo box
        
        Smena smena = term.getSmena();
        if(smena.equals(Smena.DRUGA))
            smenaCB.setSelectedIndex(1); // indeksiranje krece od 0
        if(smena.equals(Smena.TRECA))
            smenaCB.setSelectedIndex(2);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        danCB = new javax.swing.JComboBox<>();
        mesecCB = new javax.swing.JComboBox<>();
        godinaCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        smenaCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        radnikCB = new javax.swing.JComboBox<>();
        dodajButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        obrisiButton = new javax.swing.JButton();
        brisanjeTerminaButton = new javax.swing.JButton();
        zapamtiTermin = new javax.swing.JButton();
        nazadButton = new javax.swing.JButton();
        ulogaCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        napomenaTA = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Pregled termina");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel2.setText("Odabir datuma:");

        danCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "14", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesecCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        godinaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038" }));

        jLabel3.setText("Odabir smene:");

        smenaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRVA", "DRUGA", "TRECA" }));

        jLabel4.setText("Dodavanje angažovanja:");

        radnikCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dodajButton.setText("Dodaj angažovanje:");
        dodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Brisanje angažovanja:");

        obrisiButton.setText("Obriši angažovanje");
        obrisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiButtonActionPerformed(evt);
            }
        });

        brisanjeTerminaButton.setText("Brisanje termina");
        brisanjeTerminaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brisanjeTerminaButtonActionPerformed(evt);
            }
        });

        zapamtiTermin.setText("Zapamti");
        zapamtiTermin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapamtiTerminActionPerformed(evt);
            }
        });

        nazadButton.setText("Nazad");
        nazadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazadButtonActionPerformed(evt);
            }
        });

        ulogaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEF_RADIONICE", "ELEKTRICAR", "MEHANICAR", "POMOCNI_RADNIK", "SERVISNI_SAVETNIK", "MAGACIONER" }));

        jLabel6.setText("Dodaj ulogu:");

        napomenaTA.setColumns(20);
        napomenaTA.setRows(5);
        jScrollPane2.setViewportView(napomenaTA);

        jLabel7.setText("Napomena:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(smenaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(dodajButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(danCB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesecCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(godinaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ulogaCB, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)
                                        .addComponent(radnikCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(nazadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(obrisiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 448, Short.MAX_VALUE)
                                .addComponent(brisanjeTerminaButton)
                                .addGap(18, 18, 18)
                                .addComponent(zapamtiTermin)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(danCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesecCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(godinaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smenaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radnikCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ulogaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(dodajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obrisiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nazadButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brisanjeTerminaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zapamtiTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nazadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazadButtonActionPerformed
        new PrikaziTerminTabelaForma().setVisible(true);
        dispose();
    }//GEN-LAST:event_nazadButtonActionPerformed

    private void zapamtiTerminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapamtiTerminActionPerformed
        Smena smena = Smena.valueOf((String)smenaCB.getSelectedItem());
        int d = Integer.parseInt((String)danCB.getSelectedItem());
        int m = Integer.parseInt((String)mesecCB.getSelectedItem());
        int y = Integer.parseInt((String)godinaCB.getSelectedItem());
        if(DateChecker.checkDate(d, m, y) == false){
            Notification.showErrorMessage(this, "Sistem ne može da zapamti termin");
            return;
        }
        LocalDate datum = LocalDate.of(y, m, d);
        Termin td = new Termin(termin.getIdTermin(), datum, smena, termin.getListaTerminaRadnika());
        boolean signal = TerminKontroler.getInstance().promeniTermin(td);
        if(signal == true){
           Notification.showInfoMessage(this, "Sistem je zapamtio termin");
           new PrikaziTerminTabelaForma().setVisible(true);
           dispose();
           return;
        }
        Notification.showErrorMessage(this, "Sistem nije zapamtio termin");
    }//GEN-LAST:event_zapamtiTerminActionPerformed

    private void dodajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajButtonActionPerformed
        Radnik radnik = (Radnik)listRadnik.get(radnikCB.getSelectedIndex());
        for(DomainObject i : termin.getListaTerminaRadnika()){
            TerminRadnika t = (TerminRadnika) i;
            if(radnik.equals(t.getRadnik())){
                Notification.showErrorMessage(this, "Radnik je već angažovan za ovaj termin");
                return;
            }
        }
        Uloga uloga = Uloga.valueOf((String)ulogaCB.getSelectedItem());
        termin.getListaTerminaRadnika().add(new TerminRadnika(uloga, napomenaTA.getText(), radnik, termin));  //ja ne znam da li ce ovo raditi
        tabela.setModel(new TerminRadnikaModel(termin.getListaTerminaRadnika()));
    }//GEN-LAST:event_dodajButtonActionPerformed

    private void obrisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiButtonActionPerformed
        int index = tabela.getSelectedRow();
        if(index < 0){ // -1 za neodabrano
            Notification.showErrorMessage(this, "Termin radnika nije izabran");
            return;
        }
        List<DomainObject> list = termin.getListaTerminaRadnika();
        list.remove(index);
        tabela.setModel(new TerminRadnikaModel(termin.getListaTerminaRadnika()));
    }//GEN-LAST:event_obrisiButtonActionPerformed

    private void brisanjeTerminaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brisanjeTerminaButtonActionPerformed
        termin.setQueryFilter(new QueryFilter(termin));
        boolean signal = TerminKontroler.getInstance().obrisiTermin(termin);
        if(signal == true){
            Notification.showInfoMessage(this, "Sistem je obrisao termin");
            new PrikaziTerminTabelaForma().setVisible(true);
            dispose();
            return;
        }
        Notification.showErrorMessage(this, "Sistem nije uspeo da obriše termin");
    }//GEN-LAST:event_brisanjeTerminaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrikaziTerminForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brisanjeTerminaButton;
    private javax.swing.JComboBox<String> danCB;
    private javax.swing.JButton dodajButton;
    private javax.swing.JComboBox<String> godinaCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> mesecCB;
    private javax.swing.JTextArea napomenaTA;
    private javax.swing.JButton nazadButton;
    private javax.swing.JButton obrisiButton;
    private javax.swing.JComboBox<String> radnikCB;
    private javax.swing.JComboBox<String> smenaCB;
    private javax.swing.JTable tabela;
    private javax.swing.JComboBox<String> ulogaCB;
    private javax.swing.JButton zapamtiTermin;
    // End of variables declaration//GEN-END:variables
}
